coordinates:
  name: schema
  namespace: '@grafana'
  provider: npmjs
  type: npm
revisions:
  8.5.4:
    licensed:
      declared: Apache-2.0
  9.0.2:
    licensed:
      declared: Apache-2.0
  9.1.0:
    licensed:
      declared: Apache-2.0
