coordinates:
  name: applicationinsights-dependencies-js
  namespace: '@microsoft'
  provider: npmjs
  type: npm
revisions:
  2.8.18:
    licensed:
      declared: MIT
  3.3.9:
    licensed:
      declared: MIT
