coordinates:
    type: npm
    provider: npmjs
    namespace: '@microsoft'
    name: applicationinsights-core-js
revisions:
    2.8.18:
        licensed:
            declared: MIT
    3.3.4:
        licensed:
            declared: MIT
    3.3.5:
        licensed:
            declared: MIT
