coordinates:
  name: applicationinsights-common
  namespace: '@microsoft'
  provider: npmjs
  type: npm
revisions:
  2.8.18:
    licensed:
      declared: MIT
  3.3.4:
    licensed:
      declared: MIT
  3.3.5:
    licensed:
      declared: MIT
