coordinates:
  name: dependabot-dep
  provider: rubygems
  type: gem
revisions:
  0.129.5:
    licensed:
      declared: LicenseRef-scancode-prosperity-2.0
  0.145.4:
    licensed:
      declared: LicenseRef-scancode-prosperity-2.0
  0.158.0:
    licensed:
      declared: LicenseRef-scancode-prosperity-2.0
