coordinates:
  name: dependabot-npm_and_yarn
  provider: rubygems
  type: gem
revisions:
  0.145.4:
    licensed:
      declared: OTHER
  0.162.0:
    licensed:
      declared: OTHER
  0.162.2:
    licensed:
      declared: OTHER
  0.209.0:
    licensed:
      declared: OTHER
  0.215.0:
    licensed:
      declared: OTHER
  0.229.0:
    licensed:
      declared: OTHER
