coordinates:
  name: dependabot-pub
  provider: rubygems
  type: gem
revisions:
  0.209.0:
    licensed:
      declared: LicenseRef-scancode-prosperity-2.0
  0.215.0:
    licensed:
      declared: LicenseRef-scancode-prosperity-2.0
  0.229.0:
    licensed:
      declared: LicenseRef-scancode-prosperity-2.0
