coordinates:
  name: dependabot-bundler
  provider: rubygems
  type: gem
revisions:
  0.129.5:
    licensed:
      declared: LicenseRef-scancode-prosperity-2.0
  0.135.0:
    licensed:
      declared: LicenseRef-scancode-prosperity-2.0
  0.145.4:
    licensed:
      declared: LicenseRef-scancode-prosperity-2.0
  0.158.0:
    licensed:
      declared: LicenseRef-scancode-prosperity-2.0
  0.162.0:
    licensed:
      declared: LicenseRef-scancode-prosperity-2.0
  0.162.1:
    licensed:
      declared: LicenseRef-scancode-prosperity-2.0
  0.162.2:
    licensed:
      declared: LicenseRef-scancode-prosperity-2.0
  0.169.8:
    licensed:
      declared: LicenseRef-scancode-prosperity-2.0
  0.209.0:
    licensed:
      declared: LicenseRef-scancode-prosperity-2.0
  0.215.0:
    licensed:
      declared: LicenseRef-scancode-prosperity-2.0
  0.229.0:
    licensed:
      declared: LicenseRef-scancode-prosperity-2.0
