coordinates:
  name: lottie-compose
  namespace: com.airbnb.android
  provider: mavencentral
  type: maven
revisions:
  4.0.0:
    licensed:
      declared: Apache-2.0
  4.1.0:
    licensed:
      declared: Apache-2.0
